### PR TITLE
Set `ligatures` to `true` for Fantasque Sans Mono

### PR DESCRIPTION
**Pull request by kongdivin**

### CODE REVIEW

**Comment by chriscoyier** [comment]
Thanks! Ideally we'd take new screenshots too here to show them off in the characters area. Got time for that?

**Comment by kongdivin** [comment]
Actually, the current screenshots already showcase ligature.

screenshot

**Comment by chriscoyier** [comment]
It does there, but the Characters screen has an extra area just for ligatures that becomes part of these screenshot when that flag is on. See example: https://coding-fonts.css-tricks.com/fonts/fira-code/?language=charmap

**Comment by kongdivin** [comment]
Ah I see. I'll add that.

**Comment by kongdivin** [comment]
Btw, I've updated the screenshot. Thank you.

**Comment by chriscoyier** [comment]
ah yes, perfect!

**Pull request merged**
