### PR TITLE
Include L|l1iI0Oo____ string in charmap for #69

### PR DESCRIPTION
**Pull request by KasimAhmic**
Updates most screenshots for inclusion of  the L|l1iI0Oo____ text string to better showcase the side by side differences between similar characters

 - Sets font size to 24px for the charmap sample so we can fit the string
 - Updates takeScreenshots.js to show which font page is logging errors
 - Updates most charmap screenshots with Cartograph CF, MonoLisa, and Operator Mono as exceptions
 - Fixes Noto Mono's font-family declaration

### CODE REVIEW

**Comment by KasimAhmic** [comment]
I'm not 100% sure how to take screenshots of the Cartograph CF, MonoLisa, and Operator Mono fonts given that I don't own them. A second PR would likely be in order here from someone that owns them. I can open an issue ticket if needed

**Comment by chriscoyier** [comment]
> I'm not 100% sure how to take screenshots of the Cartograph CF, MonoLisa, and Operator Mono fonts given that I don't own them.

I can pull this and add them if I can. Sort of annoying, but that's kind of the point of using screenshots. By not putting the font files in the repo we avoid breaking licenses or having to pay to show them.

**Comment by KasimAhmic** [comment]
> > I'm not 100% sure how to take screenshots of the Cartograph CF, MonoLisa, and Operator Mono fonts given that I don't own them.
> 
> I can pull this and add them if I can. Sort of annoying, but that's kind of the point of using screenshots. By not putting the font files in the repo we avoid breaking licenses or having to pay to show them.

Ah gotcha, that makes sense. I suppose if

**Comment by KasimAhmic** [comment]
Apologies for the closing/reopening, finger slipped lol

> I can pull this and add them if I can. Sort of annoying, but that's kind of the point of using screenshots. By not putting the font files in the repo we avoid breaking licenses or having to pay to show them.

Gotcha, that makes sense. Worst comes to worst, we just have three images that are still just using the old screenshot. Would definitley be nice to update them though if possible.

**Comment by chriscoyier** [comment]
Should be all set.

I wonder if we should remove all the `FONT='font-name' npm run screenshots:js` stuff now with the much nicer command line setup?

**Comment by KasimAhmic** [comment]
> Should be all set.
> 
> I wonder if we should remove all the `FONT='font-name' npm run screenshots:js` stuff now with the much nicer command line setup?

Sorry, forgot to reply to this. Yeah, the NPM commands were just left in there as more of a backwards compatibility thing. Honestly didn't give much thought to it but given that they're basically just pre written `takeScreenshots.js` commands, it probably would make sense to just get rid of them entirely. I'll submit a PR shortly.

```json
    "screenshots": "npm run screenshots:js && npm run screenshots:html && npm run screenshots:css && npm run screenshots:charmap",
    "screenshots:js": "node takeScreenshots.js --lang js --theme all --font \"$FONT\"",
    "screenshots:html": "node takeScreenshots.js --lang html --theme all --font \"$FONT\"",
    "screenshots:css": "node takeScreenshots.js --lang css --theme all --font \"$FONT\"",
    "screenshots:charmap": "node takeScreenshots.js --lang charmap --theme all --font \"$FONT\"",
```

**Pull request merged**
