### PR TITLE
Update Cascadia Code features 

### PR DESCRIPTION
**Pull request by quirico**
Latest release both includes italic and cursive variants plus variable formats.

### CODE REVIEW

**Comment by quirico** [comment]
Sorry if I've messed with extra commits, it's my first PR on GitHub! 😊

**Comment by chriscoyier** [comment]
Somehow just ONE of the screenshots failed:
https://deploy-preview-110--coding-fonts.netlify.app/fonts/cascadia-code/?language=css&theme=light

**Comment by quirico** [comment]
> Somehow just ONE of the screenshots failed: https://deploy-preview-110--coding-fonts.netlify.app/fonts/cascadia-code/?language=css&theme=light

Yep, it seems that on my environment takeScreenshot.js randomly fails while producing files (node v14.18.2). Anyway, I finally managed to recreate the flawed screenshot.

**Comment by chriscoyier** [comment]
Perrrrrfect.

**Pull request merged**
