### PR TITLE
Meslo LG fonts

### PR DESCRIPTION
**Pull request by wpwood**
Added the Meslo LG fonts from https://github.com/andreberg/Meslo-Font

### CODE REVIEW

**Comment by chriscoyier** [comment]
Hey Bill,

Thanks so much!

Few thoughts...

The text here:

> I really like Menlo but I do have my nitpicky gripes with it:
> 
> The default vertical (line) spacing is just way to cramped for me, and also I am not particularily fond of the horizontal baseline alignment of the asterisk. That’s why I decided to customize Menlo, regarding these “issues”. The tricky part is keeping all the custom tables, hints, etc. intact when you adjust the globally very affecting stuff that results in vertical spacing.

Is written in first-person without it being clear who is talking. I'd rather just avoid the first-person thing at all and stick to the facts about what is happening with the font.

I also think having a whole separate font for the DZ version is unnecessary. Maybe just link up the fact that it existing in the copy for the main font.

**Comment by wpwood** [comment]
> [snip]
> Is written in first-person without it being clear who is talking. I'd rather just avoid the first-person thing at all and stick to the facts about what is happening with the font.
> 

Gotcha. Yeah, I lifted that directly from font README. I'll see about rewriting it.

> I also think having a whole separate font for the DZ version is unnecessary. Maybe just link up the fact that it existing in the copy for the main font.

Will do.

**Comment by wpwood** [comment]
@chriscoyier I have updated the description and removed the Meslo LG DZ pages.

**Comment by chriscoyier** [comment]
Perrrrrfect, thanks so much Bill!

**Pull request merged**
